In [440]:
import pandas as pd

In [441]:
berk = pd.read_csv('scrapers/berkTest.csv')
cmu = pd.read_csv('scrapers/CMUTest.csv')
corn = pd.read_csv('scrapers/cornellTest.csv')
sail = pd.read_csv('scrapers/SAILTest.csv')
uiuc = pd.read_csv('scrapers/UIUCTest.csv')
yale = pd.read_csv('scrapers/YaleTest.csv')
mit = pd.read_csv('scrapers/mitTest.csv')
stan = pd.read_csv('scrapers/stanfordTest.csv')

allData = [berk, cmu, corn, sail, uiuc, yale, mit, stan]

In [442]:
total = 0
for df in allData:
    print(df.columns)
    print()

Index(['description', 'link', 'name', 'number', 'prerequisites', 'profs',
       'text_profs', 'type', 'units', 'websites'],
      dtype='object')

Index(['background', 'key_topics', 'last_offered', 'level', 'link', 'meta',
       'name', 'number', 'permission', 'prereq', 'units', 'website'],
      dtype='object')

Index(['name', 'sites'], dtype='object')

Index(['link', 'name', 'number', 'profs'], dtype='object')

Index(['description', 'directors', 'last_updated', 'link', 'name', 'number',
       'prereq', 'website'],
      dtype='object')

Index(['date', 'description', 'link', 'name', 'number', 'professor'], dtype='object')

Index(['description', 'features', 'level', 'link', 'name', 'number',
       'taught_in'],
      dtype='object')

Index(['link', 'name', 'number', 'prof'], dtype='object')

In [443]:

allData[0].drop(columns = ['prerequisites', 'type', 'profs', 'text_profs', 'units'], inplace = True)
allData[0].rename(columns={"websites": "website"}, inplace=True)
allData[0].dropna(subset = ["website"], inplace=True)
allData[0].head()

,description,link,name,number,website
0,Foundations of data science from three perspe...,https://www2.eecs.berkeley.edu/Courses/CSC8,NaN,CS C8,http://inst.eecs.berkeley.edu/~cs8
1,"Fundamental dynamic data structures, includin...",https://www2.eecs.berkeley.edu/Courses/CS61B,The Structure and Interpretation of Computer P...,CS 61B,http://inst.eecs.berkeley.edu/~cs61b
2,An introduction to programming and computer s...,https://www2.eecs.berkeley.edu/Courses/CS61A,Self-paced courses,CS 61A,http://inst.eecs.berkeley.edu/~cs61a
3,This course allows students who have had a li...,https://www2.eecs.berkeley.edu/Courses/EECS47D...,Self-paced courses,EECS 47D,http://inst.eecs.berkeley.edu/~eecs47d
4,MIPS instruction set simulation. The assembly...,https://www2.eecs.berkeley.edu/Courses/CS47C_1977,Self-paced courses,CS 47C,http://inst.eecs.berkeley.edu/~cs47c

In [444]:
allData[1].drop(columns = ['background', 'key_topics', 'last_offered', 'level', 'units', 'meta', 'permission', 'prereq'], inplace = True)
allData[1].dropna(subset = ["website"], inplace=True)
allData[1].head()

,link,name,number,website
2,https://www.csd.cs.cmu.edu/course-profiles/15-...,Algorithms and Advanced Data Structures,15-351,http://www.cs.cmu.edu/~jianma/15351/index.html
4,https://www.csd.cs.cmu.edu/course-profiles/15-...,Algorithm Design and Analysis,15-651,"https://www.cs.cmu.edu/~15451/,https://www.cs...."
6,https://www.csd.cs.cmu.edu/course-profiles/15-...,Database Systems,15-645,http://15445.courses.cs.cmu.edu/
7,http://www.csd.cs.cmu.edu/course-profiles/15-3...,Constructive Logic,15-317,http://www.cs.cmu.edu/~fp/courses/15317-f17/
9,https://www.csd.cs.cmu.edu/course-profiles/15-...,Discrete Differential Geometry,15-458,http://geometry.cs.cmu.edu/ddg

In [445]:
def courseNum(df):
    return df['name'].split(':')[0]
def courseName(df):
    return df['name'].split(':')[len(df['name'])]
def courseName(df):
    return df['name'].split(':')[1]
def courseLink(df):
    l =  eval(df['website'])[0]
    l = list(l.values())
    if len(l) == 0:
        return ''
    return l[0]
allData[2].rename(columns={"sites": "website"}, inplace=True)
allData[2].dropna(subset = ["website"], inplace=True)
allData[2]['number'] = allData[2].apply(courseNum, axis = 1)
allData[2]['name'] = allData[2].apply(courseName, axis = 1)
allData[2]['website'] = allData[2].apply(courseLink, axis = 1)
allData[2].head()

,name,website,number
0,Fundamental Programming Concepts,https://classes.cornell.edu/browse/roster/SU20...,1109
1,Introduction to Computing Using Python,https://classes.cornell.edu/browse/roster/SP22...,1110
2,Introduction to Computing Using MATLAB,http://www.cs.cornell.edu/courses/CS1112/2021sp/,1112
3,Short Course in MATLAB,http://www.cs.cornell.edu/courses/CS1132/2021sp/,1132
4,Short Course in Python,https://classes.cornell.edu/browse/roster/SP22...,1133

In [446]:
allData[3].drop(columns = ['profs'], inplace = True)
allData[3].rename(columns={"link": "website"}, inplace=True)
allData[3].dropna(subset = ["website"], inplace=True)
allData[3].head()

,website,name,number
0,http://www.stanford.edu/class/cs124/,From Languages to Information,CS124
1,http://logic.stanford.edu/classes/cs157/current/,Computational Logic,CS157
2,http://web.stanford.edu/class/cs205l/,Continuous Mathematical Methods with an Emphas...,CS205L
3,http://www.stanford.edu/class/cs221/,Artificial Intelligence: Principles and Techni...,CS221
4,https://stanford-cs221.github.io/spring2021/,Artificial Intelligence: Principles & Techniques,CS221

In [447]:
allData[4].drop(columns = ['link','prereq','directors','last_updated'], inplace = True)
allData[4].dropna(subset = ["website"], inplace=True)
allData[4].head()

,description,name,number,website
0,Computing as an essential tool of academic and...,Intro Computing: Non-Tech,CS 105,https://go.cs.illinois.edu/105
1,A theoretical CS course covering advances in a...,Topics in Algrthmc Game Theory,CS 580,https://courses.grainger.illinois.edu/cs580/fa...
2,The purpose of the course is to give each stud...,Algorithmic Genomic Biology,CS 581,http://tandy.cs.illinois.edu/CS581-Fa2021-shor...
5,Seminar on topics of current interest as annou...,CS Colloquium,CS 591 CSO,https://courses.grainger.illinois.edu/cs591cs/...
8,Approximation algorithms for NP-hard problems....,Approximation Algorithms,CS 583,https://courses.engr.illinois.edu/cs583/fa2021/

In [448]:

combined = pd.merge(allData[0], allData[1], how="outer")
combined = pd.merge(combined, allData[2], how="outer")
combined = pd.merge(combined, allData[3], how="outer")
combined = pd.merge(combined, allData[4], how="outer")
combined.to_csv('cleanData.csv')